# Generated by Django 3.0.8 on 2020-07-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('activityapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='member',
        ),
    ]
