# Generated by Django 3.0.8 on 2020-07-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activityapi', '0004_activityperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activityapi.Member'),
        ),
    ]
